"""Convert Car's Column id from varchar to int4

Revision ID: 2f70c63f59b3
Revises: a1d137b8760a
Create Date: 2024-11-01 15:42:19.836251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f70c63f59b3'
down_revision: Union[str, None] = 'a1d137b8760a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
