"""upgraded car  table

Revision ID: d32d6867052f
Revises: 58307c63dc84
Create Date: 2024-10-03 18:13:43.242933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32d6867052f'
down_revision: Union[str, None] = '58307c63dc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('carType', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'carType')
    # ### end Alembic commands ###
